// <auto-generated />
namespace eDoc_Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UpdatePrimaryTemplateEmailTableAndDisplayNameforColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdatePrimaryTemplateEmailTableAndDisplayNameforColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202209270326472_Update Primary Template Email Table And DisplayName for Column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
